FROM python:3.10-slim-buster
WORKDIR /app
COPY . /app/
COPY requirements.txt .
RUN \
apt-get update && \
apt-get upgrade -y && \
apt-get autoremove -y && \
apt-get clean -y && \
pip install --upgrade pip && \
pip install wheel && \
pip install -r requirements.txt
ENV PORT=$port
EXPOSE $PORT
CMD uvicorn src.api:app --host 0.0.0.0 --port $PORT --reload
