n_chrom: 10
fit_expr: "1/x1**2+x2**2"
max_gen: 1000
lower_x1: 0
upper_x1: 10
lower_x2: 0
upper_x2: 10
precision: 5
crossover_rate: 0.3
mutation_rate: 0.01

# path
save_plot_path: "asset/fitness_plot.png"