FROM python:3.10.6-slim-buster
WORKDIR /app
COPY requirements.txt requirements.txt
RUN \
apt-get update && \
apt-get upgrade -y && \
apt-get autoremove -y && \
apt-get clean -y && \
pip install --upgrade pip && \
pip install wheel && \
pip install -r requirements.txt
COPY ./ ./
EXPOSE 8501
CMD ["streamlit", "run", "src/front_end.py"]